# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2748, 1547)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.display_label = QtWidgets.QLabel(self.centralwidget)
        self.display_label.setGeometry(QtCore.QRect(20, 10, 851, 91))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.display_label.setFont(font)
        self.display_label.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color:rgb(147, 255, 58);\n"
"")
        self.display_label.setObjectName("display_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(2160, 20, 541, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.connect_pi = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.connect_pi.setFont(font)
        self.connect_pi.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"            QPushButton:disabled {\n"
"        background-color:rgb(79, 79, 79);\n"
"        color:rgb(172, 172, 172)\n"
"       }")
        self.connect_pi.setObjectName("connect_pi")
        self.gridLayout_7.addWidget(self.connect_pi, 0, 0, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.connect_button.setFont(font)
        self.connect_button.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"")
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_7.addWidget(self.connect_button, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(700, 140, 2001, 1361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connection_string = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.connection_string.setGeometry(QtCore.QRect(1700, 20, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.connection_string.setFont(font)
        self.connection_string.setStyleSheet("background-color:rgb(74, 74, 74);\n"
"color: rgb(4, 213, 0);\n"
"")
        self.connection_string.setObjectName("connection_string")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 130, 641, 681))
        self.frame.setStyleSheet("            QFrame {\n"
"                border: 2px solid green;\n"
"            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(100, 320, 451, 341))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.drone_image_button = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.drone_image_button.setFont(font)
        self.drone_image_button.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"              font-size : large;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"")
        self.drone_image_button.setObjectName("drone_image_button")
        self.gridLayout_5.addWidget(self.drone_image_button, 5, 0, 1, 1)
        self.mission_button = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mission_button.setFont(font)
        self.mission_button.setStyleSheet("QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"\n"
"QPushButton:disabled {\n"
"        background-color:rgb(79, 79, 79);\n"
"        color:rgb(172, 172, 172)\n"
"}")
        self.mission_button.setAutoDefault(False)
        self.mission_button.setObjectName("mission_button")
        self.gridLayout_5.addWidget(self.mission_button, 2, 0, 1, 1)
        self.download = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.download.setFont(font)
        self.download.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"QPushButton:disabled {\n"
"        background-color:rgb(79, 79, 79);\n"
"        color:rgb(172, 172, 172)\n"
"}\n"
"")
        self.download.setObjectName("download")
        self.gridLayout_5.addWidget(self.download, 4, 0, 1, 1)
        self.arm_button = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.arm_button.setFont(font)
        self.arm_button.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"QPushButton:disabled {\n"
"        background-color:rgb(79, 79, 79);\n"
"        color:rgb(172, 172, 172)\n"
"}\n"
"")
        self.arm_button.setObjectName("arm_button")
        self.gridLayout_5.addWidget(self.arm_button, 3, 0, 1, 1)
        self.simulation_button = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.simulation_button.setFont(font)
        self.simulation_button.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"")
        self.simulation_button.setObjectName("simulation_button")
        self.gridLayout_5.addWidget(self.simulation_button, 0, 0, 1, 1)
        self.plan_button = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.plan_button.setFont(font)
        self.plan_button.setStyleSheet("        QPushButton {\n"
"            background-color: rgb(41, 152, 255); \n"
"              color: white;\n"
"              border-radius: 10px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(19, 88, 152);\n"
"              color:rgb(213, 235, 255)\n"
"        }\n"
"            QPushButton:disabled {\n"
"        background-color:rgb(79, 79, 79);\n"
"        color:rgb(172, 172, 172)\n"
"       }")
        self.plan_button.setObjectName("plan_button")
        self.gridLayout_5.addWidget(self.plan_button, 1, 0, 1, 1)
        self.missionPlaningLabel = QtWidgets.QLabel(self.frame)
        self.missionPlaningLabel.setGeometry(QtCore.QRect(0, 0, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.missionPlaningLabel.setFont(font)
        self.missionPlaningLabel.setStyleSheet("color:rgb(0, 255, 30)")
        self.missionPlaningLabel.setObjectName("missionPlaningLabel")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 70, 621, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lcd_speed_3 = QtWidgets.QLCDNumber(self.layoutWidget_6)
        self.lcd_speed_3.setStyleSheet("background-color:rgb(80, 80, 80);\n"
"color:rgb(0, 200, 40)")
        self.lcd_speed_3.setObjectName("lcd_speed_3")
        self.gridLayout_6.addWidget(self.lcd_speed_3, 1, 1, 1, 1)
        self.lcd_battery_3 = QtWidgets.QLCDNumber(self.layoutWidget_6)
        self.lcd_battery_3.setStyleSheet("background-color:rgb(80, 80, 80);\n"
"color:rgb(0, 200, 40)")
        self.lcd_battery_3.setObjectName("lcd_battery_3")
        self.gridLayout_6.addWidget(self.lcd_battery_3, 1, 2, 1, 1)
        self.lcd_altitude_3 = QtWidgets.QLCDNumber(self.layoutWidget_6)
        self.lcd_altitude_3.setStyleSheet("background-color:rgb(80, 80, 80);\n"
"color:rgb(0, 200, 40)")
        self.lcd_altitude_3.setObjectName("lcd_altitude_3")
        self.gridLayout_6.addWidget(self.lcd_altitude_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;\n"
"")
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(180, 220, 150, 62))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white;\n"
"")
        self.label_12.setObjectName("label_12")
        self.mode_label = QtWidgets.QLabel(self.frame)
        self.mode_label.setGeometry(QtCore.QRect(330, 220, 150, 62))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mode_label.setFont(font)
        self.mode_label.setStyleSheet("color:white;\n"
"background-color:rgb(75, 75, 75)")
        self.mode_label.setText("")
        self.mode_label.setObjectName("mode_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2748, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display_label.setText(_translate("MainWindow", "TextLabel"))
        self.connect_pi.setText(_translate("MainWindow", "Connect to Raspberrypi"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.connection_string.setPlainText(_translate("MainWindow", "com10"))
        self.connection_string.setPlaceholderText(_translate("MainWindow", "tcp:127.0.0.1:5762"))
        self.drone_image_button.setText(_translate("MainWindow", "Upload Drone Image"))
        self.mission_button.setText(_translate("MainWindow", "Load Mission"))
        self.download.setText(_translate("MainWindow", "Download mission data"))
        self.arm_button.setText(_translate("MainWindow", "Start"))
        self.simulation_button.setText(_translate("MainWindow", "Run Simulation"))
        self.plan_button.setText(_translate("MainWindow", "Plan a mission"))
        self.missionPlaningLabel.setText(_translate("MainWindow", "Mission Planning"))
        self.label_6.setText(_translate("MainWindow", "Speed (m/s)"))
        self.label_3.setText(_translate("MainWindow", "Altitude (m)"))
        self.label_11.setText(_translate("MainWindow", "Battery (%)"))
        self.label_12.setText(_translate("MainWindow", "Mode:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
